import Head from "next/head";

const Layout: React.FC<React.PropsWithChildren> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <svg className="absolute -z-10 h-full w-full">
            <filter id="roughpaper" x="0%" y="0%" width="100%" height="100%">
              <feTurbulence
                type="fractalNoise"
                baseFrequency="0.02"
                numOctaves="10"
              />
              <feDiffuseLighting lighting-color="#EFEFEF" surfaceScale="1.5">
                <feDistantLight azimuth="60" elevation="65" />
              </feDiffuseLighting>
            </filter>

            <rect width="100%" height="100%" filter="url(#roughpaper)" />
          </svg>
          {children}
        </div>
      </main>
    </>
  );
};

export default Layout;
