import Head from "next/head";
import UnderlineHover from "./underline-hover";
import { signIn, signOut, useSession } from "next-auth/react";
import Button from "./button";
import Link from "./link";

const Layout: React.FC<React.PropsWithChildren<{ noHeader?: boolean }>> = ({
  noHeader = false,
  children,
}) => {
  const sessionData = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-text container flex w-full flex-col items-center justify-center gap-12 px-4 py-16">
        <svg className="absolute left-0 top-0 -z-10 h-full w-full">
          <filter id="roughpaper" x="0%" y="0%" width="100%" height="100%">
            <feTurbulence
              type="fractalNoise"
              baseFrequency="0.02"
              numOctaves="10"
            />
            <feDiffuseLighting lightingColor="#EFEFEF" surfaceScale="1.5">
              <feDistantLight azimuth="60" elevation="65" />
            </feDiffuseLighting>
          </filter>

          <rect width="100%" height="100%" filter="url(#roughpaper)" />
        </svg>

        {noHeader ? (
          <></>
        ) : (
          <div className="absolute left-0 top-0 flex w-screen justify-between px-8 py-6">
            <Link href="/" variant="getBolder">
              FICTIONARY
            </Link>

            <UnderlineHover>
              <Button
                variant="blank"
                className="p-0"
                onClick={
                  sessionData.status === "authenticated"
                    ? () => signOut()
                    : () => signIn("google")
                }
              >
                {sessionData.status === "authenticated"
                  ? "SIGN OUT"
                  : "SIGN IN"}
              </Button>
            </UnderlineHover>
          </div>
        )}
        {children}
      </div>
    </>
  );
};

export default Layout;
